version: '3.8'

services:
  icecast:
    image: meu_icecast # Nome da imagem que você criou com o Dockerfile
    build: .
    container_name: icecast_server
    ports:
      - "8000:8000" # Mapeia a porta 8000 do container para a porta 8000 do host
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml # Monta o arquivo de configuração personalizado
      - logs:/var/log/icecast2 # Volume para armazenar logs
      - /etc/localtime:/etc/localtime:ro # Sincronizar o tempo do host
    environment:
      ICECAST_SOURCE_PASSWORD: hackme    # Senha para fonte
      ICECAST_ADMIN_PASSWORD: hackme     # Senha do administrador
      ICECAST_PASSWORD: hackme           # Senha padrão
      ICECAST_RELAY_PASSWORD: hackme     # Senha do relay
    restart: unless-stopped

volumes:
  logs: # Define um volume para persistência de logs

 





