services:
  icecast:
    image: moul/icecast:latest
    volumes:
      - logs:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro 
    environment:
      ICECAST_SOURCE_PASSWORD: hackme
      ICECAST_ADMIN_PASSWORD: hackme
      ICECAST_PASSWORD: hackme
      ICECAST_RELAY_PASSWORD: hackme
    ports:
      - "8000:8000"

volumes:
  logs:

