services:
  icecast:
    build: .  # Utiliza o Dockerfile presente na pasta atual para construir a imagem personalizada
    container_name: icecast_server
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do container para a porta 8000 do host
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml  # Monta o arquivo de configuração personalizado
      - ./logs:/var/log/icecast2  # Monta o diretório de logs para persistência
      - /etc/localtime:/etc/localtime:ro  # Sincroniza o tempo do host com o container
    environment:
      ICECAST_SOURCE_PASSWORD: hackme    # Senha para fonte
      ICECAST_ADMIN_PASSWORD: hackme     # Senha do administrador
      ICECAST_PASSWORD: hackme           # Senha padrão
      ICECAST_RELAY_PASSWORD: hackme     # Senha do relay
    restart: unless-stopped

volumes:
  logs:  # Define um volume para persistência de logs


 





